project_id = "iezhssfzbiwnofhpjahv"

[functions.deeplink-create]
verify_jwt = false

[functions.deeplink-validate]
verify_jwt = false

[functions.magic-link-send]
verify_jwt = false

[functions.magic-link-verify]
verify_jwt = false

[functions.set-password]
verify_jwt = true

[functions.reset-ktb-password]
verify_jwt = false

[functions.create-agent-user]
verify_jwt = false

[functions.create-stakeholder-user]
verify_jwt = false

[functions.org-invite-user]
verify_jwt = true
