// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iezhssfzbiwnofhpjahv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllemhzc2Z6Yml3bm9maHBqYWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzk4NDEsImV4cCI6MjA3NDcxNTg0MX0.lZ6mVrCKrSxza6dsbMS_2Yq5hY-trUAb-hzZGcdrcD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ---------------------------------------------------------------------------
// Global activity-log interceptor
// ---------------------------------------------------------------------------
// Wraps supabase.from(table) so that successful insert/update/delete calls
// produce an entry in public.activity_logs. Reads are intentionally ignored
// here — page-level reads are already captured by the auto page-view logger
// to avoid log spam from background refetches.

const SKIP_TABLES = new Set<string>([
  "activity_logs",       // never log writes to the log table itself
  "auth_logs",
  "integration_logs",
  "mdm_audit_log",
  "lodge_sessions",
  "ephemeral_sessions",
  "magic_tokens",
  "notifications",       // system-generated noise
  "engagement_activities",
]);

type WriteOp = "insert" | "update" | "delete" | "upsert";

const inferResource = (table: string) => table;

const buildDescription = (op: WriteOp, table: string) => {
  const verbs: Record<WriteOp, string> = {
    insert: "Created",
    upsert: "Saved",
    update: "Updated",
    delete: "Deleted",
  };
  return `${verbs[op]} ${table.replace(/_/g, " ")}`;
};

const writeActivityLog = async (op: WriteOp, table: string, payload: any) => {
  try {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return;

    // Resolve organization_id (best-effort, non-blocking on failure)
    let organizationId: string | null = null;
    const { data: userRow } = await supabase
      .from("users")
      .select("organization_id")
      .eq("user_id", user.id)
      .maybeSingle();
    organizationId = userRow?.organization_id ?? null;
    if (!organizationId) {
      const { data: orgUserRow } = await supabase
        .from("org_users")
        .select("organization_id")
        .eq("user_id", user.id)
        .eq("status", "active")
        .order("updated_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      organizationId = orgUserRow?.organization_id ?? null;
    }

    await supabase.from("activity_logs").insert({
      user_id: user.id,
      organization_id: organizationId,
      action_type: `${op}_${table}`,
      resource_type: inferResource(table),
      resource_id: null,
      metadata: {
        description: buildDescription(op, table),
        operation: op,
        table,
        ...(payload ? { payload_summary: summarizePayload(payload) } : {}),
      },
      user_agent: typeof navigator !== "undefined" ? navigator.userAgent : null,
    });
  } catch (err) {
    // Never let logging break the user action
    console.warn("[activity-log] failed", op, table, err);
  }
};

const summarizePayload = (payload: any): any => {
  try {
    const arr = Array.isArray(payload) ? payload : [payload];
    return arr.slice(0, 5).map((row) => {
      if (!row || typeof row !== "object") return row;
      const keys = Object.keys(row).slice(0, 8);
      const out: Record<string, any> = {};
      keys.forEach((k) => {
        const v = (row as any)[k];
        if (v === null || ["string", "number", "boolean"].includes(typeof v)) {
          out[k] = typeof v === "string" && v.length > 120 ? v.slice(0, 117) + "…" : v;
        }
      });
      return out;
    });
  } catch {
    return null;
  }
};

const wrapBuilder = (builder: any, table: string, op: WriteOp, payload: any) => {
  // QueryBuilder is thenable — patch .then so we can observe success.
  const originalThen = builder.then?.bind(builder);
  if (!originalThen) return builder;
  builder.then = (onFulfilled: any, onRejected: any) =>
    originalThen((res: any) => {
      if (res && !res.error) {
        void writeActivityLog(op, table, payload);
      }
      return onFulfilled ? onFulfilled(res) : res;
    }, onRejected);
  return builder;
};

const originalFrom = supabase.from.bind(supabase);
(supabase as any).from = (table: any) => {
  const builder = originalFrom(table);
  if (typeof table !== "string" || SKIP_TABLES.has(table)) return builder;

  const originalInsert = builder.insert?.bind(builder);
  const originalUpdate = builder.update?.bind(builder);
  const originalDelete = builder.delete?.bind(builder);
  const originalUpsert = builder.upsert?.bind(builder);

  if (originalInsert) {
    builder.insert = (values: any, options?: any) =>
      wrapBuilder(originalInsert(values, options), table, "insert", values);
  }
  if (originalUpdate) {
    builder.update = (values: any, options?: any) =>
      wrapBuilder(originalUpdate(values, options), table, "update", values);
  }
  if (originalDelete) {
    builder.delete = (options?: any) =>
      wrapBuilder(originalDelete(options), table, "delete", null);
  }
  if (originalUpsert) {
    builder.upsert = (values: any, options?: any) =>
      wrapBuilder(originalUpsert(values, options), table, "upsert", values);
  }

  return builder;
};